<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Failed suite [Failed suite [regression]]" duration-ms="89130" started-at="2015-08-24T16:28:09Z" finished-at="2015-08-24T16:29:38Z">
    <groups>
    </groups>
    <test name="AppContent(failed)(failed)" duration-ms="89130" started-at="2015-08-24T16:28:09Z" finished-at="2015-08-24T16:29:38Z">
      <class name="com.suite.regression.AppContent">
        <test-method status="FAIL" signature="uploadFile(java.lang.String)[pri:0, instance:com.suite.regression.AppContent@34ce8af7]" name="uploadFile" duration-ms="11" started-at="2015-08-24T21:58:55Z" data-provider="testData" finished-at="2015-08-24T21:58:55Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[./src/com/autoitfiles/upload_bmp.exe]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.suite.regression.AppContent.uploadFile(AppContent.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- uploadFile -->
      </class> <!-- com.suite.regression.AppContent -->
      <class name="com.suite.regression.Users">
        <test-method status="PASS" signature="login()[pri:0, instance:com.suite.regression.Users@2d209079]" name="login" is-config="true" duration-ms="44405" started-at="2015-08-24T21:58:09Z" finished-at="2015-08-24T21:58:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="logout()[pri:0, instance:com.suite.regression.Users@2d209079]" name="logout" is-config="true" duration-ms="42686" started-at="2015-08-24T21:58:55Z" finished-at="2015-08-24T21:59:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
      </class> <!-- com.suite.regression.Users -->
    </test> <!-- AppContent(failed)(failed) -->
  </suite> <!-- Failed suite [Failed suite [regression]] -->
</testng-results>
